-- POLICY CHANGE
INSERT INTO
    qadbtest.qa_indicators_meta (
        col_name,
        display_name,
        enable_comments,
        is_primay,
        include_general,
        include_detail,
        `order`,
        description,
        indicatorId,
        is_core,
        indicator_slug
    )
VALUES
    (
        'nutrition_tag_level',
        'Nutrition Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Nutrition Tag Level',
        8,
        0,
        NULL
    ),
    (
        'environmental_biodiversity_tag_level',
        'Environmental Biodiversity Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Environmental Biodiversity Tag Level',
        8,
        0,
        NULL
    ),
    (
        'poverty_tag_level',
        'Poverty Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Poverty Tag Level',
        8,
        0,
        NULL
    ),
    (
        'action_area',
        'Action Area',
        0,
        0,
        1,
        0,
        0,
        'Action Area',
        8,
        0,
        NULL
    ),
    (
        'impact_area_targets',
        'Impact Area Targets',
        0,
        0,
        1,
        0,
        0,
        'Impact Area Targets',
        8,
        0,
        NULL
    ),
    (
        'sdg',
        'SDG',
        0,
        0,
        1,
        0,
        0,
        'SDG',
        8,
        0,
        NULL
    ),
    (
        'result_related',
        'Result related to',
        0,
        0,
        1,
        0,
        0,
        'Result related to',
        8,
        0,
        NULL
    );

-- INNO USE
INSERT INTO
    qadbtest.qa_indicators_meta (
        col_name,
        display_name,
        enable_comments,
        is_primay,
        include_general,
        include_detail,
        `order`,
        description,
        indicatorId,
        is_core,
        indicator_slug
    )
VALUES
    (
        'nutrition_tag_level',
        'Nutrition Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Nutrition Tag Level',
        9,
        0,
        NULL
    ),
    (
        'environmental_biodiversity_tag_level',
        'Environmental Biodiversity Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Environmental Biodiversity Tag Level',
        9,
        0,
        NULL
    ),
    (
        'poverty_tag_level',
        'Poverty Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Poverty Tag Level',
        9,
        0,
        NULL
    ),
    (
        'action_area',
        'Action Area',
        0,
        0,
        1,
        0,
        0,
        'Action Area',
        9,
        0,
        NULL
    ),
    (
        'impact_area_targets',
        'Impact Area Targets',
        0,
        0,
        1,
        0,
        0,
        'Impact Area Targets',
        9,
        0,
        NULL
    ),
    (
        'sdg',
        'SDG',
        0,
        0,
        1,
        0,
        0,
        'SDG',
        9,
        0,
        NULL
    ),
    (
        'actors',
        'Actors',
        0,
        0,
        1,
        0,
        0,
        'Actors',
        9,
        0,
        NULL
    ),
    (
        'organizations',
        'Organizations',
        0,
        0,
        1,
        0,
        0,
        'Organizations',
        9,
        0,
        NULL
    ),
    (
        'other_quantitative',
        'Other quantitative measures',
        0,
        0,
        1,
        0,
        0,
        'Other quantitative measures',
        9,
        0,
        NULL
    );

-- OTHER OUTCOME
INSERT INTO
    qadbtest.qa_indicators_meta (
        col_name,
        display_name,
        enable_comments,
        is_primay,
        include_general,
        include_detail,
        `order`,
        description,
        indicatorId,
        is_core,
        indicator_slug
    )
VALUES
    (
        'nutrition_tag_level',
        'Nutrition Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Nutrition Tag Level',
        3,
        0,
        NULL
    ),
    (
        'environmental_biodiversity_tag_level',
        'Environmental Biodiversity Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Environmental Biodiversity Tag Level',
        3,
        0,
        NULL
    ),
    (
        'poverty_tag_level',
        'Poverty Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Poverty Tag Level',
        3,
        0,
        NULL
    ),
    (
        'action_area',
        'Action Area',
        0,
        0,
        1,
        0,
        0,
        'Action Area',
        3,
        0,
        NULL
    ),
    (
        'impact_area_targets',
        'Impact Area Targets',
        0,
        0,
        1,
        0,
        0,
        'Impact Area Targets',
        3,
        0,
        NULL
    ),
    (
        'sdg',
        'SDG',
        0,
        0,
        1,
        0,
        0,
        'SDG',
        3,
        0,
        NULL
    );

-- CAP SHARING
INSERT INTO
    qadbtest.qa_indicators_meta (
        col_name,
        display_name,
        enable_comments,
        is_primay,
        include_general,
        include_detail,
        `order`,
        description,
        indicatorId,
        is_core,
        indicator_slug
    )
VALUES
    (
        'nutrition_tag_level',
        'Nutrition Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Nutrition Tag Level',
        5,
        0,
        NULL
    ),
    (
        'environmental_biodiversity_tag_level',
        'Environmental Biodiversity Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Environmental Biodiversity Tag Level',
        5,
        0,
        NULL
    ),
    (
        'poverty_tag_level',
        'Poverty Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Poverty Tag Level',
        5,
        0,
        NULL
    ),
    (
        'action_area',
        'Action Area',
        0,
        0,
        1,
        0,
        0,
        'Action Area',
        5,
        0,
        NULL
    ),
    (
        'impact_area_targets',
        'Impact Area Targets',
        0,
        0,
        1,
        0,
        0,
        'Impact Area Targets',
        5,
        0,
        NULL
    ),
    (
        'sdg',
        'SDG',
        0,
        0,
        1,
        0,
        0,
        'SDG',
        5,
        0,
        NULL
    ),
    (
        'number_of_people_trained',
        'Number of People Trained',
        0,
        0,
        1,
        0,
        0,
        'Number of People Trained',
        5,
        0,
        NULL
    );

-- INNO DEV
INSERT INTO
    qadbtest.qa_indicators_meta (
        col_name,
        display_name,
        enable_comments,
        is_primay,
        include_general,
        include_detail,
        `order`,
        description,
        indicatorId,
        is_core,
        indicator_slug
    )
VALUES
    (
        'nutrition_tag_level',
        'Nutrition Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Nutrition Tag Level',
        7,
        0,
        NULL
    ),
    (
        'environmental_biodiversity_tag_level',
        'Environmental Biodiversity Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Environmental Biodiversity Tag Level',
        7,
        0,
        NULL
    ),
    (
        'poverty_tag_level',
        'Poverty Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Poverty Tag Level',
        7,
        0,
        NULL
    ),
    (
        'action_area',
        'Action Area',
        0,
        0,
        1,
        0,
        0,
        'Action Area',
        7,
        0,
        NULL
    ),
    (
        'impact_area_targets',
        'Impact Area Targets',
        0,
        0,
        1,
        0,
        0,
        'Impact Area Targets',
        7,
        0,
        NULL
    ),
    (
        'sdg',
        'SDG',
        0,
        0,
        1,
        0,
        0,
        'SDG',
        7,
        0,
        NULL
    ),
    (
        'questions',
        'Questions',
        0,
        0,
        1,
        0,
        0,
        'Questions',
        7,
        0,
        NULL
    ),
    (
        'initiatives_investment',
        'Initiatives investment',
        0,
        0,
        1,
        0,
        0,
        'Initiatives investment',
        7,
        0,
        NULL
    ),
    (
        'npp_investment',
        'Billaterals investment',
        0,
        0,
        1,
        0,
        0,
        'Billaterals investment',
        7,
        0,
        NULL
    ),
    (
        'partner_investment',
        'Partners investment',
        0,
        0,
        1,
        0,
        0,
        'Partners investment',
        7,
        0,
        NULL
    ),
    (
        'pictures',
        'Innovation visuals',
        0,
        0,
        1,
        0,
        0,
        'Innovation visuals',
        7,
        0,
        NULL
    ),
    (
        'materials',
        'Innovations reference materials',
        0,
        0,
        1,
        0,
        0,
        'Innovations reference materials',
        7,
        0,
        NULL
    ),
    (
        'actors',
        'Actors',
        0,
        0,
        1,
        0,
        0,
        'Actors',
        7,
        0,
        NULL
    ),
    (
        'anticipated',
        'Anticipated innovation user ',
        0,
        0,
        1,
        0,
        0,
        'Anticipated innovation user ',
        7,
        0,
        NULL
    );

-- OTHER OUTPUT
INSERT INTO
    qadbtest.qa_indicators_meta (
        col_name,
        display_name,
        enable_comments,
        is_primay,
        include_general,
        include_detail,
        `order`,
        description,
        indicatorId,
        is_core,
        indicator_slug
    )
VALUES
    (
        'nutrition_tag_level',
        'Nutrition Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Nutrition Tag Level',
        4,
        0,
        NULL
    ),
    (
        'environmental_biodiversity_tag_level',
        'Environmental Biodiversity Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Environmental Biodiversity Tag Level',
        4,
        0,
        NULL
    ),
    (
        'poverty_tag_level',
        'Poverty Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Poverty Tag Level',
        4,
        0,
        NULL
    ),
    (
        'action_area',
        'Action Area',
        0,
        0,
        1,
        0,
        0,
        'Action Area',
        4,
        0,
        NULL
    ),
    (
        'impact_area_targets',
        'Impact Area Targets',
        0,
        0,
        1,
        0,
        0,
        'Impact Area Targets',
        4,
        0,
        NULL
    ),
    (
        'sdg',
        'SDG',
        0,
        0,
        1,
        0,
        0,
        'SDG',
        4,
        0,
        NULL
    );

-- IMPACT
INSERT INTO
    qadbtest.qa_indicators_meta (
        col_name,
        display_name,
        enable_comments,
        is_primay,
        include_general,
        include_detail,
        `order`,
        description,
        indicatorId,
        is_core,
        indicator_slug
    )
VALUES
    (
        'nutrition_tag_level',
        'Nutrition Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Nutrition Tag Level',
        1,
        0,
        NULL
    ),
    (
        'environmental_biodiversity_tag_level',
        'Environmental Biodiversity Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Environmental Biodiversity Tag Level',
        1,
        0,
        NULL
    ),
    (
        'poverty_tag_level',
        'Poverty Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Poverty Tag Level',
        1,
        0,
        NULL
    ),
    (
        'action_area',
        'Action Area',
        0,
        0,
        1,
        0,
        0,
        'Action Area',
        1,
        0,
        NULL
    ),
    (
        'impact_area_targets',
        'Impact Area Targets',
        0,
        0,
        1,
        0,
        0,
        'Impact Area Targets',
        1,
        0,
        NULL
    ),
    (
        'sdg',
        'SDG',
        0,
        0,
        1,
        0,
        0,
        'SDG',
        1,
        0,
        NULL
    );

-- KP
INSERT INTO
    qadbtest.qa_indicators_meta (
        col_name,
        display_name,
        enable_comments,
        is_primay,
        include_general,
        include_detail,
        `order`,
        description,
        indicatorId,
        is_core,
        indicator_slug
    )
VALUES
    (
        'nutrition_tag_level',
        'Nutrition Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Nutrition Tag Level',
        6,
        0,
        NULL
    ),
    (
        'environmental_biodiversity_tag_level',
        'Environmental Biodiversity Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Environmental Biodiversity Tag Level',
        6,
        0,
        NULL
    ),
    (
        'poverty_tag_level',
        'Poverty Tag Level',
        0,
        0,
        1,
        0,
        0,
        'Poverty Tag Level',
        6,
        0,
        NULL
    ),
    (
        'action_area',
        'Action Area',
        0,
        0,
        1,
        0,
        0,
        'Action Area',
        6,
        0,
        NULL
    ),
    (
        'impact_area_targets',
        'Impact Area Targets',
        0,
        0,
        1,
        0,
        0,
        'Impact Area Targets',
        6,
        0,
        NULL
    ),
    (
        'sdg',
        'SDG',
        0,
        0,
        1,
        0,
        0,
        'SDG',
        6,
        0,
        NULL
    ),
    (
        'online_date',
        'Online date',
        0,
        0,
        1,
        0,
        0,
        'Onile date',
        6,
        0,
        NULL
    );